version: "3"

services:
  backend:
    image: "jorigot/backend:v1"
    container_name: "mia-proyecto2-backend"
    environment:
      PORT: "3000"
      APP_CLIENT_ID: "5h6pigf3ifkb6guag3078egmjo"
      COGNITO_USER_POOL_ID: "us-east-1_Aa47sBYq2"
      S3_ACCESS_KEY_ID: "AKIA37O7XABRLD774FG3"
      S3_SECRET_ACCESS_KEY_ID: "+CgATJXJgTYjERQDyn/A2NZwDxpJpzgspKY2aT/5"
      BUCKET_NAME: "appweb-201900810-p2"
      ADMIN_USER: "adminator"
      ADMIN_EMAIL: "3004272120101@ingenieria.usac.edu.gt"
      ADMIN_PASSWORD: "Admin2022"
    ports:
      - '3000:3000'
    restart: always
